application: cse521s-wsn-project
version: 1
runtime: python
api_version: 1

handlers:
- url: /media/usage-\d+-\d+-\d+.png
  script: media/usage.py
- url: /media/js/
  static_dir: media/js/
- url: /media/css/
  static_dir: media/css/
- url: /.*
  script: main.py
